# Generated by Django 3.1.3 on 2023-02-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='father_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='parents',
            name='mother_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='visitor_phone',
            field=models.CharField(max_length=13),
        ),
    ]
